### ISSUE TITLE
[SUGGESTION] Save the title owned by the player into data, and the permission is used as an additional condition.

### ISSUE THREAD

**Issue by luoxiawuchen** [NoScapeDev/SupremeTags#3]
Hello author, could you store the titles owned by players in the database instead of adding the titles owned by players only by judging the permission nodes owned by them.

It is suggested to add a command to add titles for players through design.
for example：When the permission judgment is left blank, the title will not be automatically added to the player, but will be added by the add command
```
  test:
    tag: testdisplay
    permission: []
```
/tags add <player> <identifier>  Add the specified tag for the player.
/tags view <player> Query the titles owned by players.（Display by opening a new gui interface/chat bar）
When the required permissions are set and met, they will be automatically added to the player's title warehouse.
Or, can players be added to the title by the add command only if they meet certain permissions?

Thank you for your patience in reading, developing and sharing this excellent work.

**Comment by NoScapeDev** [comment]
This was all added in new versions,

1. permission node: setting this to `none` will unlock the tag for the player.
2. `/tags set <player> <tag>` will set a new tag for the player

`/tags view` is something I can look into adding this for sure.

thanks for the suggestion <3
